INSERT INTO to_do(description, status, create_date_time, update_date_time) VALUES
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE()),
('집안일', 'closed', CURDATE(), CURDATE()),
('빨래', 'open', CURDATE(), CURDATE()),
('청소', 'open', CURDATE(), CURDATE()),
('방청소', 'open', CURDATE(), CURDATE());


INSERT INTO to_do_references(to_do_id, reference) VALUES
(2, 1),
(3, 1),
(4, 1), (4, 3),
(5, 2), (5, 1),
(6, 3), (6, 4), (6, 5), (6, 1),
(7, 3),
(8, 6), (8, 1),
(9, 7), (9, 4),

(12, 11),
(13, 11),
(14, 11), (14, 13),
(15, 12), (15, 11),
(16, 13), (16, 14), (16, 15), (16, 11),
(17, 13),
(18, 16), (18, 11),
(19, 17), (19, 14),

(22, 21),
(23, 21),
(24, 21), (24, 23),
(25, 22), (25, 21),
(26, 23), (26, 24), (26, 25), (26, 21),
(27, 23),
(28, 26), (28, 21),
(29, 27), (29, 24),

(32, 31),
(33, 31),
(34, 31), (34, 33),
(35, 32), (35, 31),
(36, 33), (36, 34), (36, 35), (36, 31),
(37, 33),
(38, 36), (38, 31),
(39, 37), (39, 34);